name: Package

on:
  push:
    branches:
      - 'beta'
#    tags:
#      - '**'
    # paths-ignore:
    #   - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    # env:
    #   CF_API_KEY: ${{ secrets.CF_API_KEY }}
    #   WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
    #   WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    #   GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Luachecdk linter
        uses: lunarmodules/luacheck@v1

      # - name: Package
      #   uses: BigWigsMods/packager@v2
