name: Package and Release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Package and Release
    runs-on: ubuntu-latest

     env:
       GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }} # GitHub
    #   CF_API_KEY: ${{ secrets.CF_API_KEY }} # CurseForge
    #   WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }} # WoWInterface
    #   WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }} # Wago


    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

#
#       - name: Package
#         uses: BigWigsMods/packager@v2
#         with:
#           args: -p 1234 -w 5678 -a he54k6BL
